school=input("학교를 입력하세요: ")
hakgua=input("학과를 입력하세요: ")
haknum=input("학번을 입력하세요: ")
name=input("이름을 입력하세요: ")
print("==============================")
print("학교:", school)
print("학과:", hakgua)
print("학번:", haknum)
print("이름:", name)
print("==============================")